name = "mcp-memory-ui"
compatibility_date = "2024-08-26"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production]
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
WORKER_URL = "https://mcp-memory-server-production.kristoffer-remback.workers.dev"

[env.preview]
compatibility_flags = ["nodejs_compat"]